# Generated by Django 5.1.2 on 2024-11-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_title', models.CharField(max_length=255)),
                ('design_catagories', models.CharField(max_length=255)),
                ('Post_imageurl', models.URLField(blank=True)),
                ('Details_imageurl', models.URLField(blank=True)),
                ('OverviewTitle', models.CharField(max_length=255)),
                ('OverviewPara', models.CharField(max_length=255)),
                ('ApproachTitle', models.CharField(max_length=255)),
                ('ApproachPara', models.CharField(max_length=255)),
            ],
        ),
    ]
