# Generated by Django 5.1.2 on 2024-11-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_design_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_post',
            name='Details_imageurl',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='design_post',
            name='Post_imageurl',
            field=models.URLField(null=True),
        ),
    ]
