# Generated by Django 5.1.2 on 2024-11-18 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_design_post_details_imageurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_post',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
