# Generated by Django 5.1.2 on 2024-11-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_design_post_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details_imageurl', models.URLField(null=True)),
                ('OverviewTitle', models.CharField(max_length=255)),
                ('OverviewPara', models.CharField(max_length=255)),
                ('ApproachTitle', models.CharField(max_length=255)),
                ('ApproachPara', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='design_post',
            name='ApproachPara',
        ),
        migrations.RemoveField(
            model_name='design_post',
            name='ApproachTitle',
        ),
        migrations.RemoveField(
            model_name='design_post',
            name='Details_imageurl',
        ),
        migrations.RemoveField(
            model_name='design_post',
            name='OverviewPara',
        ),
        migrations.RemoveField(
            model_name='design_post',
            name='OverviewTitle',
        ),
    ]
