# Generated by Django 5.1.2 on 2024-11-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_post_details_remove_design_post_approachpara_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details_imageurl', models.CharField(max_length=255)),
                ('OverviewTitle', models.CharField(max_length=255)),
                ('OverviewPara', models.TextField()),
                ('ApproachTitle', models.CharField(max_length=255)),
                ('ApproachPara', models.TextField(default='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post_Details',
        ),
    ]
