# Generated by Django 5.1.2 on 2024-11-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_designpost_delete_post_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpost',
            name='ApproachPara',
            field=models.TextField(),
        ),
    ]
