# Generated by Django 5.1.2 on 2024-11-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_designpost_approachpara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpost',
            name='Details_imageurl',
            field=models.URLField(null=True),
        ),
    ]
